# Generated by Django 5.2.11 on 2026-03-28

import django.db.models.deletion
from django.db import migrations, models


def assign_default_company(apps, schema_editor):
    Company = apps.get_model("accounts", "Company")
    Customer = apps.get_model("crm", "Customer")
    Supplier = apps.get_model("crm", "Supplier")

    tech_company, _ = Company.objects.get_or_create(
        slug="tecnologia",
        defaults={"name": "Empresa de Productos Tecnologicos", "is_active": True},
    )

    Customer.objects.filter(company__isnull=True).update(company=tech_company)
    Supplier.objects.filter(company__isnull=True).update(company=tech_company)


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_seed_companies"),
        ("crm", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="company",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="customers", to="accounts.company"),
        ),
        migrations.AddField(
            model_name="supplier",
            name="company",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="suppliers", to="accounts.company"),
        ),
        migrations.RunPython(assign_default_company, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="customer",
            name="company",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="customers", to="accounts.company"),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="company",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="suppliers", to="accounts.company"),
        ),
        migrations.AddConstraint(
            model_name="customer",
            constraint=models.UniqueConstraint(fields=("company", "name"), name="uniq_customer_company_name"),
        ),
        migrations.AddConstraint(
            model_name="supplier",
            constraint=models.UniqueConstraint(fields=("company", "name"), name="uniq_supplier_company_name"),
        ),
    ]
