# Generated by Django 5.2.11 on 2026-03-28

import django.db.models.deletion
from django.db import migrations, models


def assign_default_company(apps, schema_editor):
    Company = apps.get_model("accounts", "Company")
    Product = apps.get_model("inventory", "Product")
    InventoryMovement = apps.get_model("inventory", "InventoryMovement")

    tech_company, _ = Company.objects.get_or_create(
        slug="tecnologia",
        defaults={"name": "Empresa de Productos Tecnologicos", "is_active": True},
    )

    Product.objects.filter(company__isnull=True).update(company=tech_company)
    InventoryMovement.objects.filter(company__isnull=True).update(company=tech_company)


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_seed_companies"),
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="company",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="products", to="accounts.company"),
        ),
        migrations.AddField(
            model_name="inventorymovement",
            name="company",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="inventory_movements", to="accounts.company"),
        ),
        migrations.RunPython(assign_default_company, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="product",
            name="company",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="products", to="accounts.company"),
        ),
        migrations.AlterField(
            model_name="inventorymovement",
            name="company",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="inventory_movements", to="accounts.company"),
        ),
        migrations.AlterField(
            model_name="product",
            name="sku",
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name="product",
            name="barcode",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name="product",
            name="qr_code",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.UniqueConstraint(fields=("company", "sku"), name="uniq_product_company_sku"),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.UniqueConstraint(condition=~models.Q(barcode=""), fields=("company", "barcode"), name="uniq_product_company_barcode"),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.UniqueConstraint(condition=~models.Q(qr_code=""), fields=("company", "qr_code"), name="uniq_product_company_qr"),
        ),
    ]
