# Generated by Django 5.2.11 on 2026-05-05 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_fix_colante_product_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
