# Generated by Django 5.2.11 on 2026-05-05 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0005_add_fecha_vencimiento_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.CharField(default="otros", max_length=60),
        ),
    ]
